### ISSUE TITLE
Host a public demo version

### ISSUE THREAD

**Issue by zsims** [seek-oss/listo#7]
A public version of Listo would help people get an understanding of what it does.

**Comment by mr-beerkiss** [comment]
1. If we went the AWS route, what are the caveats/gotchas we should be aware of?
2. What other options (eg Heroku, Digital Ocean) we should consider?
3. How will the integration with Trello work? (Should demo users supply their own keys and auth against themselves?)
4. How frequently should we clean out the DB/Trello?

**Comment by zsims** [comment]
> If we went the AWS route, what are the caveats/gotchas we should be aware of?

None really, other than the normal ones that apply to everything (put it in a DMZ, authentication, etc)

> What other options (eg Heroku, Digital Ocean) we should consider?

Heroku is appealing as we can just point it to the docker image -- even easier if it's in Dockerhub.

> How will the integration with Trello work? (Should demo users supply their own keys and auth against themselves?)

Do you think this is an important part of the demo? Vs just showing the project summary? Otherwise we could do a public read-only board?

> How frequently should we clean out the DB/Trello?

That's a good point, monthly?

**Comment by mr-beerkiss** [comment]
> Heroku is appealing as we can just point it to the docker image -- even easier if it's in Dockerhub.

Maybe that's a good start, I think a few of the more niche app hosting houses have plans for open-source things. I don't even think we really need the db storage aspect for now. In fact it might even be a good incentive to abstract the dynamodb part out and replace it with a generic storage interface to make it more flexible.

> Do you think this is an important part of the demo? Vs just showing the project summary? Otherwise we could do a public read-only board?

I think the Trello part is useful because that's ultimately what people will be using to do the Triage. Perhaps we can just create a "Listo" Trello user to get a dev key we can use that isn't directly connected to SEEK's Trello. 

> That's a good point, monthly?

Sounds good.

**Comment by zsims** [comment]
ok, I'll look to get something setup. Generic storage will make it a lot easier to host a demo version. I've raised #8 which I'll look at picking up soon
